config/routes.rb
Rails40Starter::Application.routes.draw do
  resources :enquiries

  resources :affiliates

  resources :products

  resources :positions, only: [:index, :show] do
    resources :resumes
  end

  resources :resumes, only: [:show]

  resources :news
  resources :groups
  
  namespace :cpanel do
    get '/' => 'front#index', as: :front_index
    resources :site_configs
    resources :news
    resources :products
    resources :positions
    resources :slides
    resources :resumes
    get '/about' => 'front#about', as: :front_about
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  get '/about' => 'front#about', as: :front_about
  get '/corpnews' => 'front#news', as: :front_news
  get '/join' => 'front#join', as: :front_joinus
  get '/contact' => 'front#contact', as: :front_contact
  root 'front#index'

  

end

app/models/position.rb
class Position
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  field :status, type: Integer #:status, [ ['招聘中', '0'], ['暂停招聘', '1'] ]
  field :image_url_type, type: Integer #:image_url_type, [ ['员工', '0'], ['店长', '1'] ]

  mount_uploader :avatar, AvatarUploader
  
  has_many :resumes

  scope :ongoing, -> { where(:status => 0)}  
end

app/controllers/cpanel/positions_controller.rb
class Cpanel::PositionsController < Cpanel::ApplicationController
  before_action :set_cpanel_position, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cpanel_positions = Position.all
    respond_with(@cpanel_positions)
  end

  def show
    respond_with(@cpanel_position)
  end

  def new
    @cpanel_position = Position.new
    respond_with(@cpanel_position)
  end

  def edit
  end

  def create
    @cpanel_position = Position.new(cpanel_position_params)
    if @cpanel_position.save
      redirect_to cpanel_positions_path
    end

    #respond_with([:cpanel, @cpanel_position])
  end

  def update
    @cpanel_position.update(cpanel_position_params)
    redirect_to cpanel_positions_path
    # respond_with(@cpanel_position)
  end

  def destroy
    @cpanel_position.destroy
    redirect_to cpanel_positions_path
    #respond_with(@cpanel_position)
  end

  private
    def set_cpanel_position
      @cpanel_position = Position.find(params[:id])
    end

    def cpanel_position_params
      params.require(:position).permit(:title, :content, :avatar)
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    # @positions = Position.all.ongoing
    @positions = Position.all
    @position_image_manager = SiteConfig.position_image_manager
    @position_image_employee = SiteConfig.position_image_employee
    respond_with(@positions)
  end

  def show
    respond_with(@position)
  end

  def new
    @position = Position.new
    respond_with(@position)
  end

  def edit
  end

  def create
    @position = Position.new(position_params)
    @position.save
    respond_with(@position)
  end

  def update
    @position.update(position_params)
    respond_with(@position)
  end

  def destroy
    @position.destroy
    respond_with(@position)
  end

  private
    def set_position
      @position = Position.find(params[:id])
    end

    def position_params
      params.require(:position).permit(:title, :content, :status)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= simple_form_for(@position) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content, as: :text %>
    <%= f.input :status %>
    <%= f.input :image_url_type, collection: [ ['0', '店长'], ['1', '员工'] ] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<div class="content txt_h">
  
  <div class="submenu">
    <ul>      
      <li><a href="/about"><a href="/about">企业形象</a></li>
      <li><a href="/corpnews">企业新闻</a></li>
      <li class="current"><a href="/positions">在线招聘</a></li>
    </ul>
  </div>
  <h2>美丽资讯</h2>
  <hr>
  <div>
    <% @positions.each do |position| %>
      <div style="display:block;height:auto;overflow:hidden;margin:10px 0 10px 0;padding-bottom:15px;">
        <%# if position.image_url_type == 0 %>
          <%# position_image_url = @position_image_employee %>
        <%# else %>
          <%# position_image_url = @position_image_manager %>
        <%# end %>
        <img src="<%= position.avatar.url(:thumb) %>" class="aboutbrivates" style="border:5px solid #fff;box-shadow:0 0 20px #999" />
        <h2><%= position.title %></h2>
        <p style="font-size:1.2em"><%= position.content.html_safe %></p>
        <div class="btn">
          <%= link_to '详细信息', position %>
        </div>
        <div class="btn">
          <%= link_to '申请职位', new_position_resume_path(position) %>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<div class="content txt_h">
  <div class="submenu">
    <ul>      
      <li><a href="/about"><a href="/about">企业形象</a></li>
      <li><a href="/corpnews">企业新闻</a></li>
      <li class="current"><a href="/positions">在线招聘</a></li>
    </ul>
  </div>
  <h2>美丽资讯 -- 在线招聘</h2>
  <hr />
  <img src='<%= @position.avatar.url(:medium) %>' class="aboutbrivates" style="border:5px solid #fff;box-shadow:0 0 20px #999">
    <div id="position_details">
      <p id="notice"><%= notice %></p>
      <h3>职位名称：
      <%= @position.title %>
      </h3>
      <h3>职责描述：</h3>
       <div><%= @position.content.html_safe %></div>
      <div class="btn btn-default">
        <a href="#" onclick="window.history.go(-1);return false;">返回上一页</a>
      </div>
      <div class="btn btn-default">
        <%= link_to '申请职位', new_position_resume_path(@position) %>
      </div>
    </div>


</div>