config/routes.rb
Rails40Starter::Application.routes.draw do
  resources :enquiries

  resources :affiliates

  resources :products

  resources :positions, only: [:index, :show] do
    resources :resumes
  end

  resources :resumes, only: [:show]

  resources :news
  resources :groups
  
  namespace :cpanel do
    get '/' => 'front#index', as: :front_index
    resources :site_configs
    resources :news
    resources :products
    resources :positions
    resources :slides
    resources :resumes
    get '/about' => 'front#about', as: :front_about
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  get '/about' => 'front#about', as: :front_about
  get '/corpnews' => 'front#news', as: :front_news
  get '/join' => 'front#join', as: :front_joinus
  get '/contact' => 'front#contact', as: :front_contact
  root 'front#index'

  

end

app/models/group.rb
class Group
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :url, type: String

  validates_presence_of :title, :description
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:title, :description, :url)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%#= simple_form_for(@group, html: { class: "form-horizontal" }, wrapper: :horizontal_form) do |f| %>
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, as: :text, input_html: { rows: '3' } %>
    <%#= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Back', groups_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.title %></td>
        <td><%= group.description %></td>
        <td><%= group.url %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-md-12 group-title-bar">
    <div class="group-image-avatar pull-left">
      <img src="..." alt="pic..." class="img-rounded">
    </div>
    <div class="group-title">
      <p><strong>New Group</strong>
        <a class="glyphicon glyphicon-pencil link-edit-group" aria-hidden="true" arial-label="Open" data-toggle="modal" data-target="#newGroupModal" ></a>
      </p>  
    </div>
    <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newGroupModal">Open</button> -->
    <div class="modal fade" id="newGroupModal" tabindex="-1" role="dialog" aria-labelledby="newGroupModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="newGroupModalLabel">New group</h4>
          </div>
          <div class="modal-body">
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#newGroupModal').modal('show');

      $("form label[for='group_title']").after('<span style="font-size:10px;padding-left:10px"><i class="text-info">(Give a name to your group.)</i></span>');
      $("form label[for='group_description']").after('<span style="font-size:10px;padding-left:10px"><i class="text-info">(Place some words to let people know the group.)</i></span>');
    });
  </script>
</div>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @group.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @group.url %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>