config/routes.rb
Rails40Starter::Application.routes.draw do
  resources :enquiries

  resources :affiliates

  resources :products

  resources :positions, only: [:index, :show] do
    resources :resumes
  end

  resources :resumes, only: [:show]

  resources :news
  resources :groups
  
  namespace :cpanel do
    get '/' => 'front#index', as: :front_index
    resources :site_configs
    resources :news
    resources :products
    resources :positions
    resources :slides
    resources :resumes
    get '/about' => 'front#about', as: :front_about
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  get '/about' => 'front#about', as: :front_about
  get '/corpnews' => 'front#news', as: :front_news
  get '/join' => 'front#join', as: :front_joinus
  get '/contact' => 'front#contact', as: :front_contact
  root 'front#index'

  

end

app/models/news.rb
class News
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  field :image_url, type: String
end

app/controllers/cpanel/news_controller.rb
class Cpanel::NewsController < Cpanel::ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @news = News.all
    respond_with(@news)
  end

  def show
    respond_with(@news)
  end

  def new
    @news = News.new
    respond_with(@news)
  end

  def edit
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to cpanel_news_index_path
    end
    # respond_with(@news)
  end

  def update
    @news.update(news_params)
    redirect_to cpanel_news_index_path
    # respond_with(@news)
  end

  def destroy
    @news.destroy
    redirect_to cpanel_news_index_path
    #respond_with(@news)
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title, :content)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @news = News.all
    respond_with(@news)
  end

  def show
    respond_with(@news)
  end

  def new
    @news = News.new
    respond_with(@news)
  end

  def edit
  end

  def create
    @news = News.new(news_params)
    @news.save
    respond_with(@news)
  end

  def update
    @news.update(news_params)
    respond_with(@news)
  end

  def destroy
    @news.destroy
    respond_with(@news)
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title, :content)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<div class="content txt_h">
  <div class="submenu">
    <ul>
      <li><a href="/about"><a href="/about">企业形象</a></li>
      <li class="current"><a href="/corpnews">企业新闻</a></li>
      <li><a href="/positions">在线招聘</a></li>
    </ul>
  </div>
  <h2>美丽资讯 -- 企业新闻</h2>
  <hr>
  
  <h4><%= @news.title %></h4>
  <p>
    <%= @news.content.html_safe %>
  </p>
  <div class="btn">
    <a href="#" onclick="window.history.go(-1);return false;">返回</a>
  </div>

</div>