config/routes.rb
Rails40Starter::Application.routes.draw do
  resources :enquiries

  resources :affiliates

  resources :products

  resources :positions, only: [:index, :show] do
    resources :resumes
  end

  resources :resumes, only: [:show]

  resources :news
  resources :groups
  
  namespace :cpanel do
    get '/' => 'front#index', as: :front_index
    resources :site_configs
    resources :news
    resources :products
    resources :positions
    resources :slides
    resources :resumes
    get '/about' => 'front#about', as: :front_about
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  get '/about' => 'front#about', as: :front_about
  get '/corpnews' => 'front#news', as: :front_news
  get '/join' => 'front#join', as: :front_joinus
  get '/contact' => 'front#contact', as: :front_contact
  root 'front#index'

  

end

app/models/resume.rb
class Resume
  include Mongoid::Document
  field :title, type: String
  field :content, type: String
  
  field :name, type: String
  field :phone, type: String
  field :email, type: String

  validates_presence_of :name, :phone

  field :position_id, type: String
  belongs_to :position
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/cpanel/resumes_controller.rb
class Cpanel::ResumesController < Cpanel::ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  # before_action :set_position, only: [:create]

  respond_to :html

  def index
    @cpanel_resumes = Resume.all
    respond_with(@cpanel_resumes)
  end

  def show
    respond_with(@cpanel_resume)
  end

  def new
    @cpanel_resume = Resume.new
    respond_with(@cpanel_resume)
  end

  def edit
  end

  # def create
  #   @cpanel_resume = Resume.new(resume_params)
  #   @cpanel_resume[:position_id] = @position.id

  #   if @cpanel_resume.save
  #     flash[:notice] = 'Resume was successfully created.'
  #     Notifier.resume_received(@cpanel_resume).deliver 
  #   end
    
  #   respond_with(@cpanel_resume)
  # end

  def update
    @cpanel_resume.update(resume_params)
    respond_with(@cpanel_resume)
  end

  def destroy
    @cpanel_resume.destroy
    # respond_with(@cpanel_resume)
    redirect_to '/cpanel/resumes'
  end

  private
    def set_resume
      @cpanel_resume = Resume.find(params[:id])      
      # @position = Position.find(params[:position_id])
    end

    # def set_position
    #   @position = Position.find(params[:position_id])
    # end

    def resume_params
      params.require(:resume).permit(:name, :phone, :email, :avatar, :content)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_action :set_position, only: [:create]

  respond_to :html

  def index
    @resumes = Resume.all
    respond_with(@resumes)
  end

  def show
    @resume_string = SiteConfig.resume_string
    respond_with(@resume)
  end

  def new
    @resume = Resume.new
    respond_with(@resume)
  end

  def edit
  end

  def create
    @resume = Resume.new(resume_params)
    @resume[:position_id] = @position.id

    if @resume.save
      # flash[:notice] = ''
      # Notifier.resume_received(@resume).deliver 
    end
    
    respond_with(@resume)
  end

  def update
    @resume.update(resume_params)
    respond_with(@resume)
  end

  def destroy
    @resume.destroy
    respond_with(@resume)
  end

  private
    def set_resume
      @resume = Resume.find(params[:id])      
      # @position = Position.find(params[:position_id])
    end

    def set_position
      @position = Position.find(params[:position_id])
    end

    def resume_params
      params.require(:resume).permit(:name, :phone, :email, :avatar, :content)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= simple_form_for([:position, @resume]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div>
      <label>名字:</label>
      <%= f.input_field :name %>
    </div>

    <div>
      <label>电话:</label>
      <%= f.input_field :phone %>
    </div>
    <div>
      <label>邮箱:</label>
      <%= f.input_field :email %>
    </div>
    <div>
      <label>个人描述（300字以内）:</label>
      <%= f.input_field :content, as: :text %>
    </div>
    <div>
      <label>上传简历:</label>
      <%= f.input_field :avatar %>
    </div>
  </div>

  <div class="form-actions">
    
    <div class="btn btn-default">
      <a href="#" onclick="window.history.go(-1);return false;" style="font-size:13px">返回上页</a>
      <div class="btn btn-default">
      <%= f.button :submit, '提交申请' %>
    </div>
    </div>
  </div>
<% end %>

app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.title %></td>
        <td><%= resume.content %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/show.html.erb
<div class="content txt_h">
<p id="notice"><%= notice %></p>
<h2>在线申请</h2>
<hr>
<div>
  <%= @resume_string.html_safe %>
</div>
<div class="btn">
    <a href="#" onclick="window.location=('/positions');return false;">返回</a>
  </div>

</div>